### ISSUE TITLE
As an Integrator, I'd like the country code library to be OSGi ready.

### ISSUE THREAD

**Issue by peterhuffer** [codice/countrycode#2]

**Comment by bdeining** [comment]
The initial OSGi support was added in this commit : https://github.com/codice/countrycode/commit/5c4a42f96dc762a6d9c017bcb065dd7413681623.  There is definitely room for improvement here, but with this change the converter can be used in an OSGi container.

**Comment by bdeining** [comment]
Updated the package exports to include all country code packages so that the bundle is more complete.  https://github.com/codice/countrycode/pull/19

**Comment by bdeining** [comment]
I believe the aforementioned PRs make this library OSGi friendly
